name: Terraform apply
on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      pr_id:
        description: "Pull Request ID"
        required: true

permissions:
  id-token: write # This is required for requesting the JWT for AWS OIDC
  contents: read # This is required for actions/checkout
  pull-requests: write # This is required to post PR comments
  issues: write # This is required to create issues
  actions: read # This is required to download artifacts

env:
  # AWS Region to use as primary region
  AWS_REGION: us-east-1
  AWS_ROLE: "arn:aws:iam::851725390060:role/github-app-org-repo-settings-iam-role"

jobs:
  terraform_apply:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install npm modules
        run: npm install
        working-directory: ./gh-app-org-repo-settings

      - name: oidc authenticate to AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ env.AWS_ROLE }}
          role-session-name: github-actions
          aws-region: ${{ env.AWS_REGION }}

      - name: Terraform Apply Composite Action
        uses: tamu-edu/it-ae-actions-terraform-pr-apply@main
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          pr-id: ${{ github.event.inputs.pr_id }}
        env:
          TF_VAR_github_app_private_key: ${{ secrets.TF_VAR_github_app_private_key }}
          TF_VAR_github_app_app_id: ${{ secrets.TF_VAR_github_app_app_id }}
          TF_VAR_github_app_webhook_secret: ${{ secrets.TF_VAR_github_app_webhook_secret }}
